default_twitter: &default_twitter
  twitter_api_key:  'wJdieX7isQpfB915BROXbwuTH'
  twitter_api_secret: 'OhfJQWvl8c4vE8p6Mxq1eJGN96Z1URK68pc95Ce1D0RbAel1lC'

development:
  secret_key_base: 08add323145e5eef9fe791bbce7185df56b07d40880be3e9c934d00d4fedc55d485730de87b145482358edef5384e81170fa1b7770cdbe511a2fece1475bf1b0
  <<: *default_twitter

test:
  secret_key_base: 0c9c2223ae69d8a87c8dcdcae0305cc1df7e2ca9e3c1344d41989b67c64e9aca61bf58a156db912716d72e9e909037ba5ad87edc404b23a2d5dc88a053b4e272
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
